blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ GitHub Discussion
    url: https://github.com/SwitchbackTech/compass/discussions
    about: Start a GitHub discussion for general questions and feedback
  - name: ðŸ“š Documentation
    url: https://docs.compasscalendar.com
    about: Check our documentation for setup guides, API reference, and contributing guidelines
